import type { ProjectItem } from "./types";

/** Seed track-record rows from company performance sheets. */
export const defaultProjects: ProjectItem[] = [
  // 2024
  {
    id: "p2024-1",
    year: "2024",
    month: "Jan~Mar",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Pailant Korea",
    workDetail: "Mech. Install",
    projectName: "Yp Oven Demolition Converse Modification",
    published: true,
    featured: true,
  },
  {
    id: "p2024-2",
    year: "2024",
    month: "Apr~Jun",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Pailant Korea",
    workDetail: "Mech. Install",
    projectName: "Sealer & Stay Work Station Extaintion Oven Extaintion",
    published: true,
    featured: true,
  },
  {
    id: "p2024-3",
    year: "2024",
    month: "Jul~Sep",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Maintenance",
    manufacturing: "Pailant Korea",
    workDetail: "Mech. Install",
    projectName: "Ay Attach Modification",
    published: true,
    featured: false,
  },
  {
    id: "p2024-4",
    year: "2024",
    month: "Oct~Dec",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Maintenance",
    manufacturing: "Doolim Yaskawa India",
    workDetail: "Mech. Install",
    projectName:
      "Pmr Pipe Insulation Work Kin Ass Fule Dispencer Maintenance Work",
    published: true,
    featured: false,
  },
  // 2023
  {
    id: "p2023-1",
    year: "2023",
    month: "Jan~Apr",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Donghee Korea",
    workDetail: "Mech. Install",
    projectName: "Yp Line Modification",
    published: true,
    featured: true,
  },
  {
    id: "p2023-2",
    year: "2023",
    month: "May~Aug",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Kmi",
    workDetail: "Mech. Install",
    projectName: "Pt/Ed Convers Oil Tray Extaintion",
    published: true,
    featured: false,
  },
  {
    id: "p2023-3",
    year: "2023",
    month: "Sep~Dec",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Doolim Yaskawa India",
    workDetail: "Mech. Install",
    projectName: "Pcs Cover Installation",
    published: true,
    featured: false,
  },
  // 2022
  {
    id: "p2022-1",
    year: "2022",
    month: "May",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Seda Engineering India",
    workDetail: "Mech. Install",
    projectName: "Dolly Cleaning Booth Extension (Duct Water Tank Grating)",
    published: true,
    featured: false,
  },
  {
    id: "p2022-2",
    year: "2022",
    month: "Aug",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Maintenance",
    manufacturing: "Donghee Korea",
    workDetail: "Mech. Install",
    projectName: "Ubs Oven Rail Replacement",
    published: true,
    featured: false,
  },
  {
    id: "p2022-3",
    year: "2022",
    month: "Oct",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Maintenance",
    manufacturing: "Doolim Yaskawa India",
    workDetail: "Mech. Install",
    projectName: "Pcs Pipe Chok Re-Change",
    published: true,
    featured: false,
  },
  // 2021
  {
    id: "p2021-1",
    year: "2021",
    month: "Mar",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Donghee Korea",
    workDetail: "Mech. Install",
    projectName: "Ky Attach Modification",
    published: true,
    featured: false,
  },
  {
    id: "p2021-2",
    year: "2021",
    month: "Dec",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Seda Engineering India",
    workDetail: "Mech. Install",
    projectName: "Ky Ed Bath Roof Riser Pipe Modification",
    published: true,
    featured: false,
  },
  // 2020
  {
    id: "p2020-1",
    year: "2020",
    month: "Mar",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Donghee Korea",
    workDetail: "Mech. Install",
    projectName: "Qy Attach Modification + Side Lifter Re-Placement (Cts)",
    published: true,
    featured: false,
  },
  // 2019
  {
    id: "p2019-1",
    year: "2019",
    month: "Mar",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "Development",
    manufacturing: "Donghee Korea",
    workDetail: "Mech. Install",
    projectName: "Yp Line Modification",
    published: true,
    featured: false,
  },
  // 2018
  {
    id: "p2018-1",
    year: "2018",
    month: "June",
    place: "Andhra India",
    relatedAuto: "Kia Motors",
    customer: "",
    workType: "",
    manufacturing: "Donghee Korea",
    workDetail: "",
    projectName: "Fcs/Cpc Conveyor Line (Wbs,paint,ubs,cts)",
    published: true,
    featured: false,
  },
  // 2014
  {
    id: "p2014-1",
    year: "2014",
    month: "Mar",
    place: "Pune India",
    relatedAuto: "Gm",
    customer: "Gestamp India",
    workType: "",
    manufacturing: "Simpac Korea",
    workDetail: "",
    projectName: "1000 Tandem Line Re-Location Work",
    published: true,
    featured: false,
  },
  // 2013
  {
    id: "p2013-1",
    year: "2013",
    month: "Mar",
    place: "Bangalore India",
    relatedAuto: "Honda, Kawasaki",
    customer: "Musashi",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "Musashi 620ton Hitting-Forging Press Line",
    published: true,
    featured: false,
  },
  {
    id: "p2013-2",
    year: "2013",
    month: "April",
    place: "Chenni India",
    relatedAuto: "Benz Dimer",
    customer: "Myungshin India",
    workType: "",
    manufacturing: "Kmc Korea",
    workDetail: "",
    projectName: "500 Brking /1000tandam / 1500 Transfer Press Line",
    published: true,
    featured: false,
  },
  {
    id: "p2013-3",
    year: "2013",
    month: "Oct",
    place: "Delhi India",
    relatedAuto: "Maruti Suzuki",
    customer: "",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "5200 High Speed Tandem Press Line",
    published: true,
    featured: false,
  },
  // 2012
  {
    id: "p2012-1",
    year: "2012",
    month: "Feb",
    place: "Delhi India",
    relatedAuto: "Maruti Suzuki",
    customer: "Jbm",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "2500 Transfer Press Line",
    published: true,
    featured: false,
  },
  {
    id: "p2012-2",
    year: "2012",
    month: "June",
    place: "Delhi India",
    relatedAuto: "Maruti Suzuki",
    customer: "",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "5200 High Speed Tandem Press Line",
    published: true,
    featured: false,
  },
  // 2011
  {
    id: "p2011-1",
    year: "2011",
    month: "Jan",
    place: "Delhi India",
    relatedAuto: "Maruti Suzuki",
    customer: "Bell-Sonica(sumitomo)",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "1600 Transfer Press / 300 Press Coil Line Install",
    published: true,
    featured: false,
  },
  {
    id: "p2011-2",
    year: "2011",
    month: "April",
    place: "Chenni India",
    relatedAuto: "Hyundai",
    customer: "Myungshin India",
    workType: "",
    manufacturing: "Simpac Korea",
    workDetail: "",
    projectName: "800 Simpac Press Tandem Line",
    published: true,
    featured: false,
  },
  {
    id: "p2011-3",
    year: "2011",
    month: "May",
    place: "Chenni India",
    relatedAuto: "Benz Dimer",
    customer: "Myungshin India",
    workType: "",
    manufacturing: "Kmc Korea",
    workDetail: "",
    projectName: "Msgi Kmc 1500 Press Tandem Line",
    published: true,
    featured: false,
  },
  {
    id: "p2011-4",
    year: "2011",
    month: "July",
    place: "Bangalore India",
    relatedAuto: "Toyota",
    customer: "Toyota Thusho",
    workType: "",
    manufacturing: "Hitachi&Fukui Japan",
    workDetail: "",
    projectName: "H&F1500 Transfer Line Press",
    published: true,
    featured: false,
  },
  {
    id: "p2011-5",
    year: "2011",
    month: "Sep",
    place: "Chenni India",
    relatedAuto: "Nissan",
    customer: "Unipress",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "Komatsu Unipress 1600 Transfer Line Press",
    published: true,
    featured: false,
  },
  {
    id: "p2011-6",
    year: "2011",
    month: "Dec",
    place: "Bangalore India",
    relatedAuto: "Toyota",
    customer: "Toyota Thusho",
    workType: "",
    manufacturing: "Hitachi&Fukui Japan",
    workDetail: "",
    projectName: "H&F 500 Press, Sliter Line",
    published: true,
    featured: false,
  },
  // 2010
  {
    id: "p2010-1",
    year: "2010",
    month: "Feb",
    place: "Bangalore India",
    relatedAuto: "Toyota",
    customer: "Toyotetsu",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "1600ton Transfer, 800/300 Coil Press Line",
    published: true,
    featured: false,
  },
  {
    id: "p2010-2",
    year: "2010",
    month: "July",
    place: "Bangalore India",
    relatedAuto: "Toyota",
    customer: "Toyota Thusho",
    workType: "",
    manufacturing: "Amino",
    workDetail: "",
    projectName: "200 Die-Spoting Press Re-Install",
    published: true,
    featured: false,
  },
  // 2009
  {
    id: "p2009-1",
    year: "2009",
    month: "Mar",
    place: "Pune India",
    relatedAuto: "Gm",
    customer: "Dongshinmotec",
    workType: "",
    manufacturing: "Simpac Korea",
    workDetail: "",
    projectName: "1200/800/400/400 Tandem Line",
    published: true,
    featured: false,
  },
  {
    id: "p2009-2",
    year: "2009",
    month: "June",
    place: "Chenni India",
    relatedAuto: "Nissan",
    customer: "Unipress",
    workType: "",
    manufacturing: "Komatsu Japan",
    workDetail: "",
    projectName: "2000 Ton / 600 Brkanking Line",
    published: true,
    featured: false,
  },
  {
    id: "p2009-3",
    year: "2009",
    month: "Dec",
    place: "Chenni India",
    relatedAuto: "Hyundai",
    customer: "Das",
    workType: "",
    manufacturing: "Wia Korea",
    workDetail: "",
    projectName: "1200ton Progressive Press",
    published: true,
    featured: false,
  },
  // 2008
  {
    id: "p2008-1",
    year: "2008",
    month: "Aug",
    place: "Chenni India",
    relatedAuto: "Hyundai",
    customer: "Myungshin India",
    workType: "",
    manufacturing: "Rotem Korea",
    workDetail: "",
    projectName: "800/600/400/400ton Press Tandem Line",
    published: true,
    featured: false,
  },
  {
    id: "p2008-2",
    year: "2008",
    month: "Nov",
    place: "Chenni India",
    relatedAuto: "Hyundai",
    customer: "Myungshin India",
    workType: "",
    manufacturing: "Simpac Korea",
    workDetail: "",
    projectName: "Blranking 400ton & Coil Line",
    published: true,
    featured: false,
  },
];
