import type { ProjectItem } from "./types";

/** Seed track-record rows from company performance sheets. */
export const defaultProjects: ProjectItem[] = [
  // 2024
  {
    id: "p2024-1",
    year: "2024",
    month: "JAN~MAR",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "PAILANT KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "YP OVEN DEMOLITION CONVERSE MODIFICATION",
    published: true,
    featured: true,
  },
  {
    id: "p2024-2",
    year: "2024",
    month: "APR~JUN",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "PAILANT KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "SEALER & STAY WORK STATION EXTAINTION OVEN EXTAINTION",
    published: true,
    featured: true,
  },
  {
    id: "p2024-3",
    year: "2024",
    month: "JUL~SEP",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "MAINTENANCE",
    manufacturing: "PAILANT KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "AY ATTACH MODIFICATION",
    published: true,
    featured: false,
  },
  {
    id: "p2024-4",
    year: "2024",
    month: "OCT~DEC",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "MAINTENANCE",
    manufacturing: "DOOLIM YASKAWA INDIA",
    workDetail: "MECH. INSTALL",
    projectName:
      "PMR PIPE INSULATION WORK KIN ASS FULE DISPENCER MAINTENANCE WORK",
    published: true,
    featured: false,
  },
  // 2023
  {
    id: "p2023-1",
    year: "2023",
    month: "JAN~APR",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "DONGHEE KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "YP LINE MODIFICATION",
    published: true,
    featured: true,
  },
  {
    id: "p2023-2",
    year: "2023",
    month: "MAY~AUG",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "KMI",
    workDetail: "MECH. INSTALL",
    projectName: "PT/ED CONVERS OIL TRAY EXTAINTION",
    published: true,
    featured: false,
  },
  {
    id: "p2023-3",
    year: "2023",
    month: "SEP~DEC",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "DOOLIM YASKAWA INDIA",
    workDetail: "MECH. INSTALL",
    projectName: "PCS COVER INSTALLATION",
    published: true,
    featured: false,
  },
  // 2022
  {
    id: "p2022-1",
    year: "2022",
    month: "MAY",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "SEDA ENGINEERING INDIA",
    workDetail: "MECH. INSTALL",
    projectName: "DOLLY CLEANING BOOTH EXTENSION (Duct Water Tank Grating)",
    published: true,
    featured: false,
  },
  {
    id: "p2022-2",
    year: "2022",
    month: "AUG",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "MAINTENANCE",
    manufacturing: "DONGHEE KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "UBS OVEN RAIL REPLACEMENT",
    published: true,
    featured: false,
  },
  {
    id: "p2022-3",
    year: "2022",
    month: "OCT",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "MAINTENANCE",
    manufacturing: "DOOLIM YASKAWA INDIA",
    workDetail: "MECH. INSTALL",
    projectName: "PCS PIPE CHOK RE-CHANGE",
    published: true,
    featured: false,
  },
  // 2021
  {
    id: "p2021-1",
    year: "2021",
    month: "MAR",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "DONGHEE KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "KY ATTACH MODIFICATION",
    published: true,
    featured: false,
  },
  {
    id: "p2021-2",
    year: "2021",
    month: "DEC",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "SEDA ENGINEERING INDIA",
    workDetail: "MECH. INSTALL",
    projectName: "KY ED BATH ROOF RISER PIPE MODIFICATION",
    published: true,
    featured: false,
  },
  // 2020
  {
    id: "p2020-1",
    year: "2020",
    month: "MAR",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "DONGHEE KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "QY ATTACH MODIFICATION + SIDE LIFTER RE-PLACEMENT (CTS)",
    published: true,
    featured: false,
  },
  // 2019
  {
    id: "p2019-1",
    year: "2019",
    month: "MAR",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "DEVELOPMENT",
    manufacturing: "DONGHEE KOREA",
    workDetail: "MECH. INSTALL",
    projectName: "YP LINE MODIFICATION",
    published: true,
    featured: false,
  },
  // 2018
  {
    id: "p2018-1",
    year: "2018",
    month: "JUNE",
    place: "ANDHRA INDIA",
    relatedAuto: "KIA MOTORS",
    customer: "",
    workType: "",
    manufacturing: "DONGHEE KOREA",
    workDetail: "",
    projectName: "FCS/CPC CONVEYOR LINE (WBS,PAINT,UBS,CTS)",
    published: true,
    featured: false,
  },
  // 2014
  {
    id: "p2014-1",
    year: "2014",
    month: "MAR",
    place: "PUNE INDIA",
    relatedAuto: "GM",
    customer: "GESTAMP INDIA",
    workType: "",
    manufacturing: "SIMPAC KOREA",
    workDetail: "",
    projectName: "1000 Tandem Line Re-location work",
    published: true,
    featured: false,
  },
  // 2013
  {
    id: "p2013-1",
    year: "2013",
    month: "MAR",
    place: "BANGALORE INDIA",
    relatedAuto: "Honda, Kawasaki",
    customer: "MUSASHI",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "MUSASHI 620ton Hitting-Forging PRESS LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2013-2",
    year: "2013",
    month: "APRIL",
    place: "CHENNI INDIA",
    relatedAuto: "BENZ DIMER",
    customer: "MYUNGSHIN INDIA",
    workType: "",
    manufacturing: "KMC KOREA",
    workDetail: "",
    projectName: "500 Brking /1000Tandam / 1500 Transfer PRESS LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2013-3",
    year: "2013",
    month: "OCT",
    place: "DELHI INDIA",
    relatedAuto: "MARUTI SUZUKI",
    customer: "",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "5200 High Speed Tandem PRESS LINE",
    published: true,
    featured: false,
  },
  // 2012
  {
    id: "p2012-1",
    year: "2012",
    month: "FEB",
    place: "DELHI INDIA",
    relatedAuto: "MARUTI SUZUKI",
    customer: "JBM",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "2500 Transfer PRESS LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2012-2",
    year: "2012",
    month: "JUNE",
    place: "DELHI INDIA",
    relatedAuto: "MARUTI SUZUKI",
    customer: "",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "5200 High Speed Tandem PRESS LINE",
    published: true,
    featured: false,
  },
  // 2011
  {
    id: "p2011-1",
    year: "2011",
    month: "JAN",
    place: "DELHI INDIA",
    relatedAuto: "MARUTI SUZUKI",
    customer: "Bell-sonica(SUMITOMO)",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "1600 Transfer Press / 300 Press Coil line INSTALL",
    published: true,
    featured: false,
  },
  {
    id: "p2011-2",
    year: "2011",
    month: "APRIL",
    place: "CHENNI INDIA",
    relatedAuto: "HYUNDAI",
    customer: "MYUNGSHIN INDIA",
    workType: "",
    manufacturing: "SIMPAC KOREA",
    workDetail: "",
    projectName: "800 SIMPAC PRESS TANDEM LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2011-3",
    year: "2011",
    month: "MAY",
    place: "CHENNI INDIA",
    relatedAuto: "BENZ DIMER",
    customer: "MYUNGSHIN INDIA",
    workType: "",
    manufacturing: "KMC KOREA",
    workDetail: "",
    projectName: "MSGI KMC 1500 PRESS TANDEM LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2011-4",
    year: "2011",
    month: "JULY",
    place: "BANGALORE INDIA",
    relatedAuto: "TOYOTA",
    customer: "TOYOTA THUSHO",
    workType: "",
    manufacturing: "HITACHI&FUKUI JAPAN",
    workDetail: "",
    projectName: "H&F1500 Transfer Line PRESS",
    published: true,
    featured: false,
  },
  {
    id: "p2011-5",
    year: "2011",
    month: "SEP",
    place: "CHENNI INDIA",
    relatedAuto: "NISSAN",
    customer: "UNIPRESS",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "KOMATSU UNIPRESS 1600 Transfer Line PRESS",
    published: true,
    featured: false,
  },
  {
    id: "p2011-6",
    year: "2011",
    month: "DEC",
    place: "BANGALORE INDIA",
    relatedAuto: "TOYOTA",
    customer: "TOYOTA THUSHO",
    workType: "",
    manufacturing: "HITACHI&FUKUI JAPAN",
    workDetail: "",
    projectName: "H&F 500 PRESS, SLITER LINE",
    published: true,
    featured: false,
  },
  // 2010
  {
    id: "p2010-1",
    year: "2010",
    month: "FEB",
    place: "BANGALORE INDIA",
    relatedAuto: "TOYOTA",
    customer: "TOYOTETSU",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "1600TON TRANSFER, 800/300 COIL PRESS LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2010-2",
    year: "2010",
    month: "JULY",
    place: "BANGALORE INDIA",
    relatedAuto: "TOYOTA",
    customer: "TOYOTA THUSHO",
    workType: "",
    manufacturing: "AMINO",
    workDetail: "",
    projectName: "200 DIE-SPOTING PRESS RE-INSTALL",
    published: true,
    featured: false,
  },
  // 2009
  {
    id: "p2009-1",
    year: "2009",
    month: "MAR",
    place: "PUNE INDIA",
    relatedAuto: "GM",
    customer: "DONGSHINMOTEC",
    workType: "",
    manufacturing: "SIMPAC KOREA",
    workDetail: "",
    projectName: "1200/800/400/400 TANDEM LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2009-2",
    year: "2009",
    month: "JUNE",
    place: "CHENNI INDIA",
    relatedAuto: "NISSAN",
    customer: "UNIPRESS",
    workType: "",
    manufacturing: "KOMATSU JAPAN",
    workDetail: "",
    projectName: "2000 TON / 600 BRKANKING LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2009-3",
    year: "2009",
    month: "DEC",
    place: "CHENNI INDIA",
    relatedAuto: "HYUNDAI",
    customer: "DAS",
    workType: "",
    manufacturing: "WIA KOREA",
    workDetail: "",
    projectName: "1200TON PROGRESSIVE PRESS",
    published: true,
    featured: false,
  },
  // 2008
  {
    id: "p2008-1",
    year: "2008",
    month: "AUG",
    place: "CHENNI INDIA",
    relatedAuto: "HYUNDAI",
    customer: "MYUNGSHIN INDIA",
    workType: "",
    manufacturing: "ROTEM KOREA",
    workDetail: "",
    projectName: "800/600/400/400TON PRESS TANDEM LINE",
    published: true,
    featured: false,
  },
  {
    id: "p2008-2",
    year: "2008",
    month: "NOV",
    place: "CHENNI INDIA",
    relatedAuto: "HYUNDAI",
    customer: "MYUNGSHIN INDIA",
    workType: "",
    manufacturing: "SIMPAC KOREA",
    workDetail: "",
    projectName: "BLRANKING 400TON & COIL LINE",
    published: true,
    featured: false,
  },
];
